[global]
    mon host = 127.0.0.1
    auth cluster required = none
    auth service required = none
    auth client required = none
    osd pool default size = 1
    osd pool default min size = 1

[mon]
    log file = /dev/stderr

[mgr]
    log file = /dev/stderr

[osd]
    log file = /dev/stderr

[client.rgw.test]
    rgw enable apis = s3, admin, iam, sts
    log file = /dev/stdout
